logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true