app:
  mode: ${APP_MODE}
  security:
    username: ${SWAGGER_USERNAME}
    password: ${SWAGGER_PASSWORD}

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
    expiration: ${JWT_ACCESS_EXPIRATION_TIME}
  refresh:
    secret: ${JWT_REFRESH_SECRET}
    expiration: ${JWT_REFRESH_EXPIRATION_TIME}

spring:
  application:
    name: sanboongi
  profiles:
    active: ${APP_MODE}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver