app:
  mode: ${APP_MODE}
  security:
    username: ${SWAGGER_USERNAME}
    password: ${SWAGGER_PASSWORD}

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
    expiration: ${JWT_ACCESS_EXPIRATION_TIME}
  refresh:
    secret: ${JWT_REFRESH_SECRET}
    expiration: ${JWT_REFRESH_EXPIRATION_TIME}

r2:
  url: ${R2_URL}
  public-url: ${R2_PUBLIC_URL}
  bucket:
    public: ${R2_PUBLIC_BUCKET}
    private: ${R2_PRIVATE_BUCKET}
  access-id: ${R2_ACCESS_ID}
  access-secret: ${R2_ACCESS_SECRET}

rest:
  template:
    requestFactory:
      trustSelfSigned: true

spring:
  application:
    name: sanboongi
  profiles:
    active: ${APP_MODE}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      prefix: ${REDIS_PREFIX}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

social:
  apple:
    client-id: ${SOCIAL_APPLE_CLIENT_ID}